name: Deployment From Github To AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Generate Deployment Package
        run: zip -r deploy.zip dist/* package*.json
        # run: zip -r deploy.zip * .[^.]* -x "**node_modules**" "**dist**" "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: nestjs
          environment_name: nestjs-env
          version_label: "nestjs-aws-beanstalk-${{ steps.format-time.outputs.replaced }}"
          region: sa-east-1
          deployment_package: deploy.zip
